######
# spark master in EMR, cloudera etc. master would be yarn
######
sparkMaster: local[*]

# colmns that should be shard keys in kinetica (java spark only)
# this won't be used if it doesn't match incoming column name
shardKeys:
   - rowid

# any primary keys to set in Kinetica (java spark only)
# this won't be used if it doesn't match incoming column name
primaryKeys:
   - none

# wkt geom that will be endoded as geometry in Kinetica (java spark only)
# this won't be used if it doesn't match incoming column name
wktFields:
   - geom

# what to encode as dictionary. low cardinality columns are good examples - e.g. gender, color
# this won't be used if it doesn't match incoming column name (java only)
dictFields:


# defines jdbc properties to pull from
# For full list of options See: https://spark.apache.org/docs/latest/sql-data-sources-jdbc.html
relationalOpts:
   url: jdbc:postgresql://vzwtesting.cbskrfjahvxo.us-east-1.rds.amazonaws.com/postgres
   dbtable: (select rowid, enodebid, cov_uuid, st_astext(geom) as geom from ca5) as temptbl
   user: postgres
   password: passwd
   driver: org.postgresql.Driver
   fetchsize: 500
   numPartitions: 500
   partitionColumn: rowid
   lowerBound: 1
   upperBound: 26925

sparkOpts:
  spark.jars: /tmp/kinetica-spark-sql-extract-1.0-SNAPSHOT-uber.jar
  spark.driver.memory: 32g
  spark.executor.memory: 32g
  spark.memory.offHeap.enabled: true
  spark.memory.offHeap.size: 32g

# This section defines the kinetica connection and ingestion configuration
# For full list of options See: https://www.kinetica.com/docs/connectors/spark_guide.html#property-reference for full list of valid options
kineticaIngest:
   database.url: http://172.30.1.10:9191
   database.jdbc_url: jdbc:kinetica://172.30.1.10:9191;ParentSet=test
   database.username: admin
   database.password: passwd
   ingester.batch_size: 500
   ingester.num_threads: 4
   table.name: vz_1
   table.create: false
   
